-- 코드를 입력하세요
SELECT ugb.TITLE, ugb.BOARD_ID, ugr.REPLY_ID, ugr.WRITER_ID, ugr.CONTENTS, TO_CHAR(ugr.CREATED_DATE, 'YYYY-MM-DD')
FROM   USED_GOODS_BOARD ugb
INNER JOIN USED_GOODS_REPLY ugr
ON ugb.BOARD_ID = ugr.BOARD_ID
WHERE ugb.CREATED_DATE >= TO_DATE('2022-10-01', 'YYYY-MM-DD')
AND ugb.CREATED_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
ORDER BY ugr.CREATED_DATE, ugb.TITLE;